security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, roles: ROLE_ADMIN }
        - { path: ^/api/inscription, roles: PUBLIC_ACCESS }
        - { path: ^/api/utilisateurs/, roles: PUBLIC_ACCESS }
        - { path: ^/api/changePass, roles: ROLE_USER }
        - { path: ^/api/publications, roles: PUBLIC_ACCESS }
        - { path: ^/api/commentaires, roles: PUBLIC_ACCESS }
        - { path: ^/api/ratingCommentaire, roles: PUBLIC_ACCESS }
        - { path: ^/api/ratingPublication, roles: PUBLIC_ACCESS }
        - { path: ^/api/user, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/myself, roles: PUBLIC_ACCESS }
        - { path: ^/api/ban, roles: PUBLIC_ACCESS }
        - { path: ^/api/unban, roles: PUBLIC_ACCESS }
        - { path: ^/api/lock, roles: PUBLIC_ACCESS }
        - { path: ^/api/unlock, roles: PUBLIC_ACCESS }
        - { path: ^/api/arrayRatingPost, roles: PUBLIC_ACCESS }
        - { path: ^/api/arrayRatingCom, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
